require("dotenv").config();

const ALTINN_MELDINGER_WEB_SESSION_NAME = process.env.ALTINN_MELDINGER_WEB_SESSION_NAME;
const ALTINN_MELDINGER_WEB_SESSION_SECRET = process.env.ALTINN_MELDINGER_WEB_SESSION_SECRET;

const FRONTEND_API_PATH = process.env.FRONTEND_API_PATH;
const BACKEND_API_PATH = process.env.BACKEND_API_PATH;
const BACKEND_BASEURL = process.env.BACKEND_BASEURL;

const AZURE_APP_CLIENT_ID = process.env.AZURE_APP_CLIENT_ID;
const AZURE_APP_JWKS = process.env.AZURE_APP_JWKS;
const AZURE_APP_WELL_KNOWN_URL = process.env.AZURE_APP_WELL_KNOWN_URL;
const OAUTH2_ON_BEHALF_SCOPE = process.env.OAUTH2_ON_BEHALF_SCOPE;
const OAUTH2_REDIRECT_URI = process.env.OAUTH2_REDIRECT_URI;


module.exports = {
    ALTINN_MELDINGER_WEB_SESSION_NAME,
    ALTINN_MELDINGER_WEB_SESSION_SECRET,
    BACKEND_BASEURL,
    BACKEND_API_PATH,
    FRONTEND_API_PATH,
    AZURE_APP_CLIENT_ID,
    AZURE_APP_JWKS,
    AZURE_APP_WELL_KNOWN_URL,
    OAUTH2_ON_BEHALF_SCOPE,
    OAUTH2_REDIRECT_URI
};
